version: 0.2

phases:
  install:
    commands:
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_TOKEN
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/i2c7a5l2
      -
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - docker build -t zcoders-danyllo-paws-pet .
      - docker save hello-app | gzip > zcoders-danyllo-paws-pet.tar.gz
      - docker tag zcoders-danyllo-paws-pet:latest public.ecr.aws/i2c7a5l2/zcoders-danyllo-paws-pet:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push public.ecr.aws/i2c7a5l2/zcoders-danyllo-paws-pet:latest
artifacts:
  files:
    - target/paws-pets-0.0.1-SNAPSHOT.jar
    - scripts/**/*
    - zcoders-danyllo-paws-pet.tar.gz
    - appspec.yml
